version: '3.6'
services:
  app:
    build:
      args:
        user: allanbzr
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ancora
    container_name: app-ancora
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ancora

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-ancora
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - ancora

  db:
    image: mysql:5.7
    container_name: db-ancora
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - ancora

networks:
  ancora:
    driver: bridge
